/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAgentOperationsRouteImport } from './routes/ai-agent-operations'
import { Route as AiAgentStudioRouteImport } from './routes/ai-agent-studio'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AiTrainerRouteImport } from './routes/ai-trainer'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BusinessOsRouteImport } from './routes/business-os'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SmartOperationsRouteImport } from './routes/smart-operations'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as AiChatPublicKeyRouteImport } from './routes/ai-chat.$publicKey'
import { Route as BookSlugRouteImport } from './routes/book.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentOperationsRoute = AiAgentOperationsRouteImport.update({
  id: '/ai-agent-operations',
  path: '/ai-agent-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentStudioRoute = AiAgentStudioRouteImport.update({
  id: '/ai-agent-studio',
  path: '/ai-agent-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTrainerRoute = AiTrainerRouteImport.update({
  id: '/ai-trainer',
  path: '/ai-trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOsRoute = BusinessOsRouteImport.update({
  id: '/business-os',
  path: '/business-os',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartOperationsRoute = SmartOperationsRouteImport.update({
  id: '/smart-operations',
  path: '/smart-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatPublicKeyRoute = AiChatPublicKeyRouteImport.update({
  id: '/ai-chat/$publicKey',
  path: '/ai-chat/$publicKey',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent-operations': typeof AiAgentOperationsRoute
  '/ai-agent-studio': typeof AiAgentStudioRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-trainer': typeof AiTrainerRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/bookings': typeof BookingsRoute
  '/business-os': typeof BusinessOsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/developer': typeof DeveloperRoute
  '/forms': typeof FormsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/plans': typeof PlansRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/smart-operations': typeof SmartOperationsRoute
  '/staff': typeof StaffRoute
  '/waitlist': typeof WaitlistRoute
  '/ai-chat/$publicKey': typeof AiChatPublicKeyRoute
  '/book/$slug': typeof BookSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent-operations': typeof AiAgentOperationsRoute
  '/ai-agent-studio': typeof AiAgentStudioRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-trainer': typeof AiTrainerRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/bookings': typeof BookingsRoute
  '/business-os': typeof BusinessOsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/developer': typeof DeveloperRoute
  '/forms': typeof FormsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/plans': typeof PlansRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/smart-operations': typeof SmartOperationsRoute
  '/staff': typeof StaffRoute
  '/waitlist': typeof WaitlistRoute
  '/ai-chat/$publicKey': typeof AiChatPublicKeyRoute
  '/book/$slug': typeof BookSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent-operations': typeof AiAgentOperationsRoute
  '/ai-agent-studio': typeof AiAgentStudioRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-trainer': typeof AiTrainerRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/automations': typeof AutomationsRoute
  '/bookings': typeof BookingsRoute
  '/business-os': typeof BusinessOsRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRoute
  '/developer': typeof DeveloperRoute
  '/forms': typeof FormsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/plans': typeof PlansRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/smart-operations': typeof SmartOperationsRoute
  '/staff': typeof StaffRoute
  '/waitlist': typeof WaitlistRoute
  '/ai-chat/$publicKey': typeof AiChatPublicKeyRoute
  '/book/$slug': typeof BookSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent-operations'
    | '/ai-agent-studio'
    | '/ai-assistant'
    | '/ai-trainer'
    | '/analytics'
    | '/auth'
    | '/automations'
    | '/bookings'
    | '/business-os'
    | '/calendar'
    | '/customers'
    | '/developer'
    | '/forms'
    | '/notifications'
    | '/onboarding'
    | '/packages'
    | '/plans'
    | '/resources'
    | '/reviews'
    | '/services'
    | '/settings'
    | '/smart-operations'
    | '/staff'
    | '/waitlist'
    | '/ai-chat/$publicKey'
    | '/book/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent-operations'
    | '/ai-agent-studio'
    | '/ai-assistant'
    | '/ai-trainer'
    | '/analytics'
    | '/auth'
    | '/automations'
    | '/bookings'
    | '/business-os'
    | '/calendar'
    | '/customers'
    | '/developer'
    | '/forms'
    | '/notifications'
    | '/onboarding'
    | '/packages'
    | '/plans'
    | '/resources'
    | '/reviews'
    | '/services'
    | '/settings'
    | '/smart-operations'
    | '/staff'
    | '/waitlist'
    | '/ai-chat/$publicKey'
    | '/book/$slug'
  id:
    | '__root__'
    | '/'
    | '/ai-agent-operations'
    | '/ai-agent-studio'
    | '/ai-assistant'
    | '/ai-trainer'
    | '/analytics'
    | '/auth'
    | '/automations'
    | '/bookings'
    | '/business-os'
    | '/calendar'
    | '/customers'
    | '/developer'
    | '/forms'
    | '/notifications'
    | '/onboarding'
    | '/packages'
    | '/plans'
    | '/resources'
    | '/reviews'
    | '/services'
    | '/settings'
    | '/smart-operations'
    | '/staff'
    | '/waitlist'
    | '/ai-chat/$publicKey'
    | '/book/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentOperationsRoute: typeof AiAgentOperationsRoute
  AiAgentStudioRoute: typeof AiAgentStudioRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AiTrainerRoute: typeof AiTrainerRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  AutomationsRoute: typeof AutomationsRoute
  BookingsRoute: typeof BookingsRoute
  BusinessOsRoute: typeof BusinessOsRoute
  CalendarRoute: typeof CalendarRoute
  CustomersRoute: typeof CustomersRoute
  DeveloperRoute: typeof DeveloperRoute
  FormsRoute: typeof FormsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PackagesRoute: typeof PackagesRoute
  PlansRoute: typeof PlansRoute
  ResourcesRoute: typeof ResourcesRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SmartOperationsRoute: typeof SmartOperationsRoute
  StaffRoute: typeof StaffRoute
  WaitlistRoute: typeof WaitlistRoute
  AiChatPublicKeyRoute: typeof AiChatPublicKeyRoute
  BookSlugRoute: typeof BookSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent-operations': {
      id: '/ai-agent-operations'
      path: '/ai-agent-operations'
      fullPath: '/ai-agent-operations'
      preLoaderRoute: typeof AiAgentOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent-studio': {
      id: '/ai-agent-studio'
      path: '/ai-agent-studio'
      fullPath: '/ai-agent-studio'
      preLoaderRoute: typeof AiAgentStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-trainer': {
      id: '/ai-trainer'
      path: '/ai-trainer'
      fullPath: '/ai-trainer'
      preLoaderRoute: typeof AiTrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-os': {
      id: '/business-os'
      path: '/business-os'
      fullPath: '/business-os'
      preLoaderRoute: typeof BusinessOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-operations': {
      id: '/smart-operations'
      path: '/smart-operations'
      fullPath: '/smart-operations'
      preLoaderRoute: typeof SmartOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat/$publicKey': {
      id: '/ai-chat/$publicKey'
      path: '/ai-chat/$publicKey'
      fullPath: '/ai-chat/$publicKey'
      preLoaderRoute: typeof AiChatPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentOperationsRoute: AiAgentOperationsRoute,
  AiAgentStudioRoute: AiAgentStudioRoute,
  AiAssistantRoute: AiAssistantRoute,
  AiTrainerRoute: AiTrainerRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  AutomationsRoute: AutomationsRoute,
  BookingsRoute: BookingsRoute,
  BusinessOsRoute: BusinessOsRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRoute,
  DeveloperRoute: DeveloperRoute,
  FormsRoute: FormsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PackagesRoute: PackagesRoute,
  PlansRoute: PlansRoute,
  ResourcesRoute: ResourcesRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SmartOperationsRoute: SmartOperationsRoute,
  StaffRoute: StaffRoute,
  WaitlistRoute: WaitlistRoute,
  AiChatPublicKeyRoute: AiChatPublicKeyRoute,
  BookSlugRoute: BookSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
